### ISSUE TITLE
parsing pre-input parameters?

### ISSUE THREAD

**Issue by VictorPranchere** [ColorlabMD/FFCommand_Engine#1]
When parsing a command, the parameters placed before the input file disappear.

If I try to parse a command such as
-r 16 -i input -c:v prores_ks profile:v 3 -crf 23 output.mov
then "16" will appear as a parameter in the input file command section, and the "-r" won't be present at all.

It can be corrected manually though.

**Comment by taschenbach** [comment]
The software is assuming "ffmpeg " will be the first term(ffmpeg -r 16 -i input -c:v prores_ks profile:v 3 -crf 23 output.mov). The input and output commands of the software should be the same as the command that could be usable in a terminal window. I will add a more documentation.
