### ISSUE TITLE
Start FFCommand_Engine ??

### ISSUE THREAD

**Issue by rowe-morehouse** [ColorlabMD/FFCommand_Engine#12]
I don't understand this step:

Start FFCommand\_Engine

which file launches the app? … how do you "Start FFCommand\_Engine" ?? 

thanks in advance! :)

**Comment by retokromer** [comment]
I guess, you did download the source code? The compiled version for macOS or Windows are actually the [FFCommand_Engine](https://github.com/ColorlabMD/FFCommand_Engine/releases/tag/V0.5) app.

**Comment by rowe-morehouse** [comment]
ok.

**Comment by retokromer** [comment]
@rowe-morehouse: If you are on macOS and use Homebrew, then you can install the current HEAD:
```
brew tap avpres/formulae
brew install --HEAD avpres/formulae/ffcommand-engine
```
