### ISSUE TITLE
ffmpeg exiting with an error

### ISSUE THREAD

**Issue by retokromer** [ColorlabMD/FFCommand_Engine#4]
If the exit status from the `ffmpeg` call is different than 0, then the corresponding line of the “Process Queue” window should not say “completed”, but “error”.

**Comment by taschenbach** [comment]
You are correct I will be updating shortly. Thank you.

**Comment by retokromer** [comment]
@taschenbach Any news on this? I’m asking, because we’ll use the _FFCommand_Engine_ in one month time at the IASA conference.

**Comment by taschenbach** [comment]
@retokromer the code has been updated and it now indicates an error when FFmpeg exit status is !=0. I will have releases up this weekend.

**Comment by retokromer** [comment]
@taschenbach Could you possibly publish a new release by end of next week? Thank you!

**Comment by retokromer** [comment]
Hello @taschenbach, any news about another release?

**Comment by retokromer** [comment]
This tiny error is indeed fixed in version 0.6, but users have to compile this version themselves. The last versions available here are 0.5 for Windows and 0.51 for macOS, if I am not missing something.

A few months ago, I wrote a [Homebrew formula](https://github.com/AVpres/homebrew-formulae/blob/master/ffcommand-engine.rb) for the installation of the HEAD on macOS. And I opened PRs [here](https://github.com/ColorlabMD/FFCommand_Engine/pulls) regarding a few nits which I saw when doing it.

@taschenbach Could you possibly provide the compiling guide for Linux and Windows as well? I would like to write the Makefiles also for these.

**Comment by retokromer** [comment]
visibly no interest, closing
